/**
 * Showcase assets for the public landing page. Every SVG here is REAL
 * renderer output — generated by apps/web/scripts/generate-showcase.ts with
 * the same pipeline that serves previews and the GitHub Action, then
 * committed as source assets (logged-out visitors can't reach the
 * session-gated preview API). Regenerate:
 *
 *   pnpm --filter @makeitbeauty/renderer exec tsx ../web/scripts/generate-showcase.ts
 *
 * width/height are the SVG canvas sizes — kept explicit so <img> elements
 * reserve layout space before the asset loads (no CLS).
 */
import contributionHeatmap from "@/assets/showcase/contribution-heatmap.svg";
import glowStat from "@/assets/showcase/glow-stat.svg";
import gradientBanner from "@/assets/showcase/gradient-banner.svg";
import profileCard from "@/assets/showcase/profile-card.svg";
import profileHeader from "@/assets/showcase/profile-header.svg";
import progressBar from "@/assets/showcase/progress-bar.svg";
import terminalCard from "@/assets/showcase/terminal-card.svg";

export interface ShowcaseAsset {
  src: string;
  width: number;
  height: number;
  alt: string;
  /** Kit component the render came from — shown as the strip caption. */
  label: string;
}

/** Hero centerpiece: several kit components composed on one canvas. */
export const heroCard: ShowcaseAsset = {
  src: profileCard,
  width: 800,
  height: 650,
  alt: "Composed profile card rendered by MakeItBeauty: profile header for Ada Lovelace, a contribution heatmap, two glowing stat cards and a language bar on a dark canvas",
  label: "composed profile card",
};

/** Smaller cards floating around the hero centerpiece. */
export const heroFloaters: readonly ShowcaseAsset[] = [
  {
    src: progressBar,
    width: 504,
    height: 96,
    alt: "Progress bar card showing TypeScript at 41 percent with an animated fill",
    label: "kit/progress-bar",
  },
  {
    src: terminalCard,
    width: 608,
    height: 228,
    alt: "Terminal window card typing the command npx makeitbeauty render readme.json with a blinking cursor",
    label: "kit/terminal-card",
  },
];

/** The rest of the curated set — the live examples strip. */
export const exampleStrip: readonly ShowcaseAsset[] = [
  {
    src: contributionHeatmap,
    width: 744,
    height: 164,
    alt: "GitHub-style contribution heatmap card rendered from a year of calendar data",
    label: "kit/contribution-heatmap",
  },
  {
    src: gradientBanner,
    width: 768,
    height: 188,
    alt: "Purple gradient banner card reading Build in the open, designed with MakeItBeauty",
    label: "kit/gradient-banner",
  },
  {
    src: profileHeader,
    width: 744,
    height: 144,
    alt: "Profile header card for Ada Lovelace, @ada, 1234 followers",
    label: "kit/profile-header",
  },
  {
    src: glowStat,
    width: 336,
    height: 196,
    alt: "Glowing stat card showing 5,678 total stars with an animated cyan-to-fuchsia underline",
    label: "kit/glow-stat",
  },
];
